// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

export interface PublicCommSetConfBenefitRequest {
  /** 不传仅返回用户信息 */
  benefit_type?: common.BenefitType;
  /** 必填。这里指的是Coze的AccountID */
  coze_account_id?: string;
  coze_account_type?: common.CozeAccountType;
  enterprise_id?: string;
  counter?: common.CommonCounter;
}

export interface PublicCommSetConfBenefitResponse {
  code: number;
  message: string;
}
/* eslint-enable */
