// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface EmptyData {}

export interface EmptyResp {
  code?: Int64;
  msg?: string;
  data?: EmptyData;
}
/* eslint-enable */
