import { uniqueId } from 'lodash-es';

import {
  defaultConversationKey,
  defaultConversationUniqId,
} from '../../src/const/community';

// Mimicking the uniqueId function of lodash-es
vi.mock('lodash-es', () => ({
  uniqueId: vi.fn().mockReturnValue('mocked-unique-id'),
}));

describe('const/community', () => {
  test('defaultConversationKey should be -1', () => {
    expect(defaultConversationKey).toBe(-1);
  });

  test('defaultConversationUniqId should be a unique ID generated by lodash-es', () => {
    // Verify that the uniqueId function is called
    expect(uniqueId).toHaveBeenCalled();
    // Verify that defaultConversationUniqId value is returned by the simulated uniqueId function
    expect(defaultConversationUniqId).toBe('mocked-unique-id');
  });
});
