// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface LandingPageEmailSubscribeRequest {
  email?: string;
}

export interface LandingPageEmailSubscribeResponse {
  code?: Int64;
  msg?: string;
}
/* eslint-enable */
