// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface AppAgentData {
  agent_id?: Int64;
  /** 最低可展示的版本号 */
  min_app_version?: string;
}

export interface AppUpdateData {
  /** 最新版本号 */
  last_app_version?: string;
  /** 最低可用的app版本号，低于该版本触发升级弹窗 */
  min_app_version?: string;
  /** 升级弹窗标题 */
  update_title?: string;
  /** 升级弹窗文案 */
  update_desc?: string;
  /** 最新版本链接 */
  android_update_url?: string;
  /** 最新版本链接 */
  ios_update_url?: string;
}

export interface GetAppInfoData {
  app_update?: AppUpdateData;
  /** 允许展示的agent列表 */
  expert_agent?: Array<AppAgentData>;
}

export interface GetAppInfoRequest {}

export interface GetAppInfoResponse {
  code?: Int64;
  msg?: string;
  data?: GetAppInfoData;
}
/* eslint-enable */
