// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum UserScriptTemplateType {
  UNSPECIFIED = 0,
  /** 标签任务 */
  ItemLabel = 1,
  /** 常规数据处理任务 */
  DataProcess = 2,
  /** 转为训练数据集 */
  FineTuning = 3,
}

export interface UserScriptTemplate {
  /** 模版类型 */
  user_script_template_type?: UserScriptTemplateType;
  /** 模版内容 */
  template?: string;
}
/* eslint-enable */
