// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as base from './base';
import * as batch_infer from './batch_infer';

export type Int64 = string | number;

export interface OpenGetBatchInferTaskReq {
  task_id?: string;
  userJwtToken?: string;
  /** 空间ID */
  space_id?: string;
  base?: base.Base;
}

export interface OpenGetBatchInferTaskResp {
  batchInferTask?: batch_infer.BatchInferTask;
  baseResp?: base.BaseResp;
}

export interface OpenReportBatchInferProgressReq {
  task_id?: string;
  errorMsg?: string;
  /** 空间ID */
  space_id?: string;
  base?: base.Base;
}

export interface OpenReportBatchInferProgressResp {
  baseResp?: base.BaseResp;
}
/* eslint-enable */
