// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as dataprocess from './dataprocess';
import * as base from './base';

export type Int64 = string | number;

export interface GetUserScriptTemplateRequest {
  template_type?: dataprocess.UserScriptTemplateType;
  base?: base.Base;
}

export interface GetUserScriptTemplateResponse {
  template?: dataprocess.UserScriptTemplate;
  baseResp?: base.BaseResp;
}
/* eslint-enable */
