import { isString } from 'lodash-es';

/**
 * The value generated by ai may contain expressions for {{xxx}} that will hit rehaje
 * Ignore it for the time being, and the problem can be lifted after replacing the form engine.
 */
export const ignoreRehajeExpressionString = (value: unknown) => {
  if (!isString(value)) {
    return value;
  }
  const reg = /\{\{.*\}\}/;
  return value.match(reg) ? undefined : value;
};
