

brokerClusterName = DefaultCluster
# Disable Disk Usage Alerts
# min:1, max:95
diskMaxUsedSpaceRatio=95.0

brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# Use the host Internet Protocol Address to ensure direct access from the client side
brokerIP1 = 127.0.0.1
