// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

export interface Annotation {
  id?: string;
  span_id?: string;
  trace_id?: string;
  workspace_id?: string;
  start_time?: string;
  type?: string;
  key?: string;
  value_type?: string;
  value?: string;
  status?: string;
  reasoning?: string;
  base_info?: common.BaseInfo;
  auto_evaluate?: AutoEvaluate;
  manual_feedback?: ManualFeedback;
}

export interface AutoEvaluate {
  evaluator_version_id: string;
  evaluator_name: string;
  evaluator_version: string;
  evaluator_result?: EvaluatorResult;
  record_id: string;
  task_id: string;
}

export interface Correction {
  score?: number;
  explain?: string;
  base_info?: common.BaseInfo;
}

export interface EvaluatorResult {
  score?: number;
  correction?: Correction;
  reasoning?: string;
}

export interface ManualFeedback {
  tag_key_id: string;
  tag_key_name: string;
  tag_value_id?: string;
  tag_value?: string;
}
/* eslint-enable */
