// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface BaseInfo {
  created_by?: UserInfo;
  updated_by?: UserInfo;
  created_at?: string;
  updated_at?: string;
}

export interface OrderBy {
  field?: string;
  is_asc?: boolean;
}

export interface UserInfo {
  name?: string;
  en_name?: string;
  avatar_url?: string;
  avatar_thumb?: string;
  open_id?: string;
  union_id?: string;
  user_id?: string;
  email?: string;
}
/* eslint-enable */
