// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface AnnotationEvaluator {
  evaluator_version_id: Int64;
  evaluator_name: string;
  evaluator_version: string;
}

export interface IntelligenceInfo {
  intelligence_id?: Int64;
  intelligence_name?: string;
}

export interface ListIntelligencesRequest {
  workspace_id: string;
  intelligence_type: string;
}

export interface ListIntelligencesResponse {
  intelligences: Array<IntelligenceInfo>;
}
/* eslint-enable */
