// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as span from './span';

export type Int64 = string | number;

export interface IngestTracesRequest {
  spans?: Array<span.InputSpan>;
}

export interface IngestTracesResponse {
  code?: number;
  msg?: string;
}
/* eslint-enable */
