// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface FieldOptions {
  i64_list?: Array<string>;
  f64_list?: Array<number>;
  string_list?: Array<string>;
}

export interface FilterField {
  field_name?: string;
  field_type?: string;
  values?: Array<string>;
  query_type?: string;
  query_and_or?: string;
  sub_filter?: FilterFields;
}

export interface FilterFields {
  query_and_or?: string;
  filter_fields: Array<FilterField>;
}
/* eslint-enable */
