// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface View {
  id: string;
  enterprise_id?: string;
  workspace_id?: string;
  view_name: string;
  platform_type?: string;
  spanList_type?: string;
  filters: string;
  is_system: boolean;
}
/* eslint-enable */
