// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export enum OceanProjectStatus {
  Deleted = 0,
  Using = 1,
}
/* eslint-enable */
