// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

export interface GetFunctionResourcePackagesRequest {
  /** Whether the function is a plugin function */
  is_plugin_function?: boolean;
  /** Whether the function is a worker */
  is_worker?: boolean;
  /** Runtime type to filter packages */
  runtime?: string;
  /** Region to query packages for */
  region?: string;
  /** Whether the function is triggered by MQ event */
  is_mq_event_trigger?: boolean;
  /** Function category */
  category?: string;
  /** PSM name */
  psm?: string;
  /** Parent PSM ID */
  psm_parent_id?: Int64;
}

export interface GetFunctionResourcePackagesResponse {
  code: number;
  data: Array<common.ResourceLimitWithAlias>;
  error: string;
}

export interface GetPackageListRequest {
  /** Region to query packages for */
  region: string;
}

export interface GetPackageListResponse {
  code: number;
  data: Array<Package>;
  error: string;
}

export interface Package {
  /** Package name */
  name: string;
  /** Resource limits and alias for the package */
  resource_limit: common.ResourceLimitWithAlias;
}
/* eslint-enable */
