// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface DataMessage55 {
  /** Region name */
  region: string;
}

export interface GetDeployedRegionsRequest {
  /** Service ID */
  service_id: string;
  /** JWT token for authentication */
  'X-Jwt-Token'?: string;
}

export interface GetDeployedRegionsResponse {
  code?: number;
  data?: Array<DataMessage55>;
  error?: string;
}
/* eslint-enable */
