// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

export interface SubscribeServiceRequest {
  /** JWT token for authentication */
  'X-Jwt-Token'?: string;
  /** ID of function service */
  service_id: string;
  /** 订阅人列表
array of name of subscribers. */
  subscribers?: Array<string>;
}

export interface SubscribeServiceResponse {
  code?: number;
  data?: common.ApiResponseDataMessage2;
  error?: string;
}

export interface UnsubscribeServiceRequest {
  'X-Jwt-Token'?: string;
  /** ID of service to unsub */
  service_id: string;
}

export interface UnsubscribeServiceResponse {
  code?: number;
  data?: common.ApiResponseDataMessage2;
  error?: string;
}
/* eslint-enable */
