// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface DownloadTemplateByNameRequest {
  /** Template name to download */
  template_name: string;
}

export interface DownloadTemplateByNameResponse {}

/** Function template definition */
export interface FunctionTemplate {
  /** Template description */
  description?: string;
  /** Documentation for the template */
  document?: string;
  /** Programming language of the template */
  language?: string;
  /** Template name */
  name?: string;
  /** Protocol type */
  protocol?: string;
  /** runtime. Optional values: golang/v1,node10/v1,python3/v1,rust1/v1,java8/v1,wasm/v1,v8/v1,native/v1,native-java8/v1 */
  runtime?: string;
  /** Source location of the template */
  source_location?: string;
  /** Author of the template */
  template_author?: string;
}

export interface getFunctionTemplatesRequest {}

export interface GetFunctionTemplatesResponse {
  code?: number;
  data?: Array<FunctionTemplate>;
  error?: string;
}

export interface GetTemplateByNameRequest {
  /** Template name to query */
  template_name: string;
}

export interface GetTemplateByNameResponse {
  code?: number;
  data?: FunctionTemplate;
  error?: string;
}

export interface UploadTemplateByNameRequest {
  /** Template name to upload */
  template_name: string;
}

export interface UploadTemplateByNameResponse {
  code?: number;
  data?: string;
  error?: string;
}
/* eslint-enable */
