// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import * as common from './common';

export type Int64 = string | number;

export interface ListPipelineTemplatesRequest {
  /** JWT token for authentication */
  'X-Jwt-Token'?: string;
}

export interface ListPipelineTemplatesResponse {
  code?: number;
  data?: Array<common.PipelineTemplateLegacy>;
  error?: string;
}

export interface QueryPipelineTemplateByTypeRequest {
  /** Template type */
  template_type: string;
  /** JWT token for authentication */
  'X-Jwt-Token'?: string;
}

export interface QueryPipelineTemplateByTypeResponse {
  code?: number;
  data?: common.PipelineTemplateLegacy;
  error?: string;
}
/* eslint-enable */
