// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface BucketMeta {
  /** Bucket ID */
  id?: string;
  /** Bucket name */
  name?: string;
}

export interface GetTosBucketsRequest {
  /** Region of the service */
  region: string;
  /** JWT token for authentication */
  'X-Jwt-Token'?: string;
}

export interface GetTosBucketsResponse {
  /** Response code */
  code?: number;
  /** List of bucket metadata */
  data?: Array<BucketMeta>;
  /** Error message, if any */
  error?: string;
}
/* eslint-enable */
