// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface TriggerFrozenActiveRequest {
  /** PSM name */
  psm: string;
  /** Environment name */
  env: string;
  /** Region where the service is located */
  region: string;
  /** Cluster name */
  cluster: string;
  /** Zone name */
  zone: string;
}

export interface TriggerFrozenActiveResponse {
  /** API response code */
  code: number;
  /** Response data containing log information */
  data: TriggerFrozenActiveResponseData;
  /** Error message if operation failed */
  error: string;
}

export interface TriggerFrozenActiveResponseData {
  /** Unique identifier for the log entry */
  log_id: string;
}
/* eslint-enable */
