// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type Int64 = string | number;

export interface GetVolcSigninTokenRequest {
  /** Service ID for which to obtain the sign-in token */
  service_id?: string;
  /** Region of the service */
  region?: string;
  /** Cluster of the service */
  cluster?: string;
}

export interface GetVolcSigninTokenResponse {
  code: number;
  data: GetVolcSigninTokenResponseData;
  error: string;
}

export interface GetVolcSigninTokenResponseData {
  /** Sign-in token for Volcengine authentication */
  signin_token: string;
}

export interface GetVolcTlsConfigRequest {
  /** Service ID for which to obtain TLS config */
  service_id?: string;
  /** Region of the service */
  region?: string;
  /** Cluster of the service */
  cluster?: string;
}

export interface GetVolcTlsConfigResponse {
  code: number;
  data: GetVolcTlsConfigResponseData;
  error: string;
}

export interface GetVolcTlsConfigResponseData {
  /** Whether logging is enabled for Volcengine TLS */
  enable_log: boolean;
  /** Project ID for Volcengine TLS (optional) */
  tls_project_id?: string;
  /** Topic ID for Volcengine TLS (optional) */
  tls_topic_id?: string;
}
/* eslint-enable */
